### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Pingva74** [alexandarp/terraform-gke#2]
Hello.
I get an error when I follow your instructions: 
"Error: googleapi: Error 403: Google Compute Engine: Required 'compute.networks.get' permission for 'projects/projeckt/global/networks/default'., forbidden"
How can I debug it?

**Comment by alexandarp** [comment]
It sounds like your service account doesn't have the proper permission.

What permissions does your service account have?

**Comment by Pingva74** [comment]
yes, you are right. Thanks!

**Comment by alexandarp** [comment]
No problem!
